version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      test-and-build-tooling:
        patterns:
          - '@playwright/*'
          - '@stryker-mutator/*'
          - '@vitest/*'
          - typescript
          - vite
          - vitest
          - tsx
          - typedoc
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
