import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { validateEvidenceBindings } from '../scripts/validate-evidence-bindings';

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

async function bindingFixture(): Promise<{
  directory: string;
  evidencePath: string;
  reportPath: string;
  evidence: Record<string, unknown>;
  sourceCommit: string;
}> {
  const directory = await mkdtemp(join(tmpdir(), 'pendulum-evidence-binding-'));
  temporaryDirectories.push(directory);
  await mkdir(join(directory, 'reports'));
  const reportPath = join(directory, 'reports', 'source.json');
  const reportBytes = '{"generatedAt":"2026-08-25T00:00:00.000Z","pass":true}\n';
  await writeFile(reportPath, reportBytes, 'utf8');
  const sourceCommit = 'a'.repeat(40);
  const generatedAt = '2026-08-25T00:00:00.000Z';
  const expiresAt = '2026-09-08T00:00:00.000Z';
  const reportSha256 = createHash('sha256').update(reportBytes).digest('hex');
  const evidence = {
    schemaVersion: 'pendulum-evidence-summary/v1',
    generatedAt,
    sourceReports: { source: 'reports/source.json' },
    sourceReportSha256: {
      'reports/source.json': reportSha256
    },
    provenance: { sourceCommit, dirtyWorktree: false, expiresAt },
    claims: [
      {
        id: 'tests.unit',
        displayValue: '1 / 1 pass',
        status: 'passed',
        sourceReport: 'reports/source.json',
        sourceCommit,
        evidenceGeneratedAt: generatedAt
      }
    ],
    claimEvidence: {
      schemaVersion: 'pendulum-claim-evidence-surface/v1',
      evaluatedAt: generatedAt,
      loadState: 'loaded',
      evidenceGeneratedAt: generatedAt,
      evidenceSourceCommit: sourceCommit,
      evidenceExpiresAt: expiresAt,
      counts: { withheld: 0, informational: 0, measured: 0, validated: 1, 'publication-ready': 0 },
      claims: [
        {
          id: 'tests.unit',
          defaultVisibleLevel: 'validated',
          effectiveVisibleLevel: 'validated',
          validity: 'current',
          validFrom: generatedAt,
          displayValue: '1 / 1 pass',
          evidenceStatus: 'passed',
          sourceArtifact: 'reports/source.json',
          sourceArtifactSha256: reportSha256,
          caveats: []
        }
      ]
    }
  };
  const evidencePath = join(directory, 'evidence-summary.json');
  await writeFile(evidencePath, `${JSON.stringify(evidence)}\n`, 'utf8');
  return { directory, evidencePath, reportPath, evidence, sourceCommit };
}

describe('post-generation evidence byte bindings', () => {
  it('accepts exact generated bytes and rejects later report tampering', async () => {
    const fixture = await bindingFixture();
    await expect(
      validateEvidenceBindings({
        evidencePath: fixture.evidencePath,
        reportRoot: fixture.directory,
        expectedCiSourceCommit: fixture.sourceCommit
      })
    ).resolves.toEqual({ reportCount: 1, claimCount: 1, sourceCommit: fixture.sourceCommit });

    await writeFile(fixture.reportPath, '{"pass":false}\n', 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('Evidence source report SHA-256 mismatch: reports/source.json');
  });

  it('requires exact hash-map coverage, current CI provenance, and dated claims', async () => {
    const fixture = await bindingFixture();
    const extraHash = structuredClone(fixture.evidence) as {
      sourceReportSha256: Record<string, string>;
      claims: Array<Record<string, unknown>>;
    };
    extraHash.sourceReportSha256['reports/extra.json'] = 'b'.repeat(64);
    await writeFile(fixture.evidencePath, `${JSON.stringify(extraHash)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('sourceReportSha256 keys must exactly match');

    delete extraHash.sourceReportSha256['reports/extra.json'];
    extraHash.claims[0]!.evidenceGeneratedAt = null;
    await writeFile(fixture.evidencePath, `${JSON.stringify(extraHash)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('evidenceGeneratedAt is missing or invalid');

    extraHash.claims[0]!.evidenceGeneratedAt = '2026-08-25T00:00:00.000Z';
    await writeFile(fixture.evidencePath, `${JSON.stringify(extraHash)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({
        evidencePath: fixture.evidencePath,
        reportRoot: fixture.directory,
        expectedCiSourceCommit: 'c'.repeat(40)
      })
    ).rejects.toThrow('current GitHub Actions source commit');
  });

  it('rejects canonical claim drift, leaked withheld values, and incorrect level counts', async () => {
    const fixture = await bindingFixture();
    const broken = structuredClone(fixture.evidence) as {
      claimEvidence: {
        counts: Record<string, number>;
        claims: Array<Record<string, unknown>>;
      };
    };
    broken.claimEvidence.claims[0]!.sourceArtifactSha256 = 'b'.repeat(64);
    await writeFile(fixture.evidencePath, `${JSON.stringify(broken)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('source artifact binding mismatch');

    broken.claimEvidence.claims[0]!.sourceArtifactSha256 = (
      fixture.evidence.sourceReportSha256 as Record<string, string>
    )['reports/source.json'];
    broken.claimEvidence.claims[0]!.effectiveVisibleLevel = 'withheld';
    await writeFile(fixture.evidencePath, `${JSON.stringify(broken)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('must omit a withheld display value');

    broken.claimEvidence.claims[0]!.displayValue = null;
    broken.claimEvidence.counts = { withheld: 0, informational: 0, measured: 0, validated: 1, 'publication-ready': 0 };
    await writeFile(fixture.evidencePath, `${JSON.stringify(broken)}\n`, 'utf8');
    await expect(
      validateEvidenceBindings({ evidencePath: fixture.evidencePath, reportRoot: fixture.directory })
    ).rejects.toThrow('counts do not match');
  });
});
