/**
 * Deterministic generator for the hardware-comparison fixture dataset.
 *
 * Emulates the *measurement chain* of a phone-camera double-pendulum
 * experiment: a known ground-truth pendulum is integrated at fine dt, sampled
 * at camera frame rate, projected to pixel coordinates (pivot offset, y-down
 * image convention, px/m scale), and corrupted with sub-pixel tracking noise.
 * The output is exactly what a video tracker (e.g. Tracker / OpenCV) exports:
 * `time,x1,y1,x2,y2` rows in pixels.
 *
 * HONESTY LABEL: this is a synthetic camera emulation, NOT real footage. It
 * exists so the theory-vs-measurement pipeline (import → angle extraction →
 * Levenberg–Marquardt parameter recovery → residual report) is executable and
 * regression-tested end-to-end today; swap in a real tracked CSV with the same
 * schema to make the chapter fully experimental (docs/hardware-validation.md).
 *
 * Deterministic: seeded mulberry32 PRNG + fixed-step RK4, so the committed
 * fixture is exactly reproducible with `npm run fixture:hardware`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { rhsDouble } from '../src/physics/double';
import { rk4Step } from '../src/physics/integrators';
import type { PendulumParameters } from '../src/types/domain';

// --- Ground truth (what a real experimenter would measure independently) ----
const TRUTH: PendulumParameters = { m1: 0.23, m2: 0.125, l1: 0.32, l2: 0.24, g: 9.799 };
const GAMMA = 0.035; // light pivot friction, from a separate decay measurement
const INITIAL: [number, number, number, number] = [0.42, -0.61, 0, 0]; // released from rest

// --- Camera / tracker emulation --------------------------------------------
const FPS = 60;
const DURATION_S = 6;
const PIXELS_PER_METER = 540;
const PIVOT_PX = { x: 960, y: 240 };
const TRACKING_NOISE_PX = 0.7; // 1σ sub-pixel tracker jitter
const SEED = 20260710;

const SIM_DT = 5e-4; // finer than the fit's forward-model dt (2e-3) on purpose

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a += 0x6d2b79f5;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Box–Muller gaussian from two uniforms. */
function gaussianPair(random: () => number): [number, number] {
  const u1 = Math.max(random(), Number.MIN_VALUE);
  const u2 = random();
  const radius = Math.sqrt(-2 * Math.log(u1));
  return [radius * Math.cos(2 * Math.PI * u2), radius * Math.sin(2 * Math.PI * u2)];
}

async function main(): Promise<void> {
  const random = mulberry32(SEED);
  const state = new Float64Array(INITIAL);
  const out = new Float64Array(4);
  const rhs = (s: Float64Array, o: Float64Array): void => {
    rhsDouble(s, TRUTH, GAMMA, o);
  };

  const frames = Math.round(FPS * DURATION_S) + 1;
  // Sub-step each frame so steps × dt equals the frame interval *exactly* —
  // rounding steps while keeping dt fixed would skew the time base (a ~1%
  // clock error biases the fitted g by ~2%, since g scales with time²).
  const stepsPerFrame = Math.max(1, Math.round(1 / FPS / SIM_DT));
  const frameDt = 1 / FPS / stepsPerFrame;
  const rows: string[] = ['# Synthetic camera emulation of a tracked double pendulum - NOT real footage.',
    '# Generated by scripts/generate-hardware-fixture.ts (seeded, reproducible).',
    '# Schema matches a video-tracker export: pixel coordinates, y-down, pivot offset.',
    'time,x1,y1,x2,y2'];

  for (let frame = 0; frame < frames; frame += 1) {
    const t = frame / FPS;
    const [theta1, theta2] = [state[0]!, state[1]!];
    // y-down image convention: y grows downward, so a hanging bob has +cos.
    const x1m = TRUTH.l1 * Math.sin(theta1);
    const y1m = TRUTH.l1 * Math.cos(theta1);
    const x2m = x1m + TRUTH.l2 * Math.sin(theta2);
    const y2m = y1m + TRUTH.l2 * Math.cos(theta2);
    const [n1, n2] = gaussianPair(random);
    const [n3, n4] = gaussianPair(random);
    const px1 = PIVOT_PX.x + x1m * PIXELS_PER_METER + TRACKING_NOISE_PX * n1;
    const py1 = PIVOT_PX.y + y1m * PIXELS_PER_METER + TRACKING_NOISE_PX * n2;
    const px2 = PIVOT_PX.x + x2m * PIXELS_PER_METER + TRACKING_NOISE_PX * n3;
    const py2 = PIVOT_PX.y + y2m * PIXELS_PER_METER + TRACKING_NOISE_PX * n4;
    rows.push(`${t.toFixed(6)},${px1.toFixed(2)},${py1.toFixed(2)},${px2.toFixed(2)},${py2.toFixed(2)}`);

    if (frame < frames - 1) {
      for (let s = 0; s < stepsPerFrame; s += 1) {
        rk4Step(state, frameDt, rhs, out);
        state.set(out);
      }
    }
  }

  await mkdir('data/experimental', { recursive: true });
  await writeFile('data/experimental/double-pendulum-tracker.csv', `${rows.join('\n')}\n`, 'utf8');

  const meta = {
    schemaVersion: 'hardware-fixture-meta/v1',
    provenance: {
      kind: 'synthetic-camera-emulation',
      realFootage: false,
      generator: 'scripts/generate-hardware-fixture.ts',
      seed: SEED,
      note: 'Replace the CSV with a real tracked export (same schema) and update this metadata to make the chapter fully experimental.'
    },
    camera: { fps: FPS, durationSeconds: DURATION_S, pixelsPerMeter: PIXELS_PER_METER, trackingNoisePx1Sigma: TRACKING_NOISE_PX },
    import: { pivot: PIVOT_PX, yAxis: 'down' },
    protocol: 'released from rest (omega1 = omega2 = 0 at t = 0)',
    truth: { ...TRUTH, gamma: GAMMA, initialState: INITIAL },
    fit: {
      // What the comparison CLI should estimate vs hold fixed, mirroring a real
      // bench workflow: masses from a scale, damping from a decay measurement,
      // lengths + local g recovered from the dynamics.
      estimate: ['l1', 'l2', 'g'],
      initialGuess: [0.3, 0.3, 9.5],
      fixed: { m1: TRUTH.m1, m2: TRUTH.m2, gamma: GAMMA }
    }
  };
  await writeFile('data/experimental/double-pendulum-tracker.meta.json', `${JSON.stringify(meta, null, 2)}\n`, 'utf8');
  console.log(`Wrote data/experimental/double-pendulum-tracker.csv (${frames} frames @ ${FPS} fps) + meta.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
